### PR TITLE
Added sun, moon, and local time

### PR DESCRIPTION
**Pull request by a1rb4Ck**
Based on bHogan suggestions, I found it really great, so I simply put his changes here and keep all credits to him. Hope it may help. I also added a bool usePM if you need or not a 24h day display. See here for bHogan originals : https://github.com/squix78/esp8266-weather-station/issues/32

### CODE REVIEW

**Comment by squix78** [comment]
Thank you a lot @a1rb4Ck and @bHogan2 for your work!

**Comment by bHogan2** [comment]
My pleasure!

**Comment by stony2k** [comment]
Hey bHogan2,

Would you mind to add some astronomy frames to the example?

**Comment by a1rb4Ck** [comment]
In waiting for bHogan2's nice sun rise and fall pictures, this is my not so nice implementation: https://github.com/a1rb4Ck/esp8266-weather-station-platformio-demo/blob/DEV/src/main.cpp#L364

**Comment by squix78** [comment]
Looks cool! Any chance to get some pics or a video for posting on my blog/Twitter?

**Comment by bHogan2** [comment]
Daniel,
Sorry, I don't have the time to upload the new lib and re-install my changes, but here are the routines I used for sun and moon (2 separate frames).

// My Sun frame
void drawFrame4(OLEDDisplay *display,  OLEDDisplayUiState* state, int16_t x, int16_t y) {
  ui.setTimePerFrame(frameTime);               // default frame time
  display->setFont(ArialMT_Plain_24);
  display->setTextAlignment(TEXT_ALIGN_CENTER);
  String SunriseTime = wunderground.getSunriseTime();
  display->drawString(75 + x, 0 + y, SunriseTime);
  String SunsetTime = wunderground.getSunsetTime();
  display->drawString(75 + x, 30 + y, SunsetTime);

  display->setFont(Meteocons_Plain_21);
  display->setTextAlignment(TEXT_ALIGN_LEFT);
  display->drawString(x + 10, y + 4, "1");
  display->drawString(x + 10, y + 34, "J");
}

// My Moon frame
void drawFrame5(OLEDDisplay *display,  OLEDDisplayUiState* state, int16_t x, int16_t y) {
  ui.setTimePerFrame(frameTime);               // default frame time
  display->setFont(ArialMT_Plain_16);
  display->setTextAlignment(TEXT_ALIGN_CENTER);
  //String MoonAge = wunderground.getMoonAge(); // not used
  String MoonPctIlum = wunderground.getMoonPctIlum();
  String MoonPhase = wunderground.getMoonPhase();
  display->drawString(64 + x, 0 + y, MoonPhase);
  display->drawString(64 + x, 16 + y, MoonPctIlum + "% full");

Maybe that will help.
I replaced 'precipitation' in that frame with wind speed and direction...
// Humidity, Pressure, Wind Speed and direction
void drawFrame2(OLEDDisplay *display,  OLEDDisplayUiState* state, int16_t x, int16_t y) {
  ui.setTimePerFrame(frameTime + 2000);        // add 2 seconds for this frame
  display->setTextAlignment(TEXT_ALIGN_CENTER);
  display->setFont(ArialMT_Plain_10);
  display->drawString(32 + x, 0 + y, "Humidity");
  display->drawString(96 + x, 0 + y, "Pressure");
  display->drawString(32 + x, 28 + y, "Wind Speed");
  display->drawString(96 + x, 28 + y, "Direction");

  display->setFont(ArialMT_Plain_16);
  display->drawString(32 + x, 10 + y, wunderground.getHumidity());
  display->drawString(96 + x, 10 + y, wunderground.getPressure());
  //display->drawString(32 + x, 38 + y, wunderground.getPrecipitationToday());
  display->drawString(32 + x, 38 + y, wunderground.getWindSpeed());
  display->drawString(96 + x, 38 + y, wunderground.getWindDir());
}

For what this is worth!
John

**Pull request merged**
